networks:
  retrospective-network:

services:
  # MYSQL
  mysql8-service:
    image: mysql:8
    container_name: mysql8-retrospective-container
    ports:
      - "5306:3306"
    volumes:
      - mysql8-retrospective-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: retrospective_db
      MYSQL_USER: retrospective_user
      MYSQL_PASSWORD: admin12345
    networks:
      - retrospective-network

  # PHP_MY_ADMIN
  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    depends_on:
      - mysql8-service
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql8-service
      MYSQL_ROOT_PASSWORD: admin12345
    networks:
      - retrospective-network

  ######################## RABBIT MQ #########################

  # TODO -> SETUP RabbitMQ

  ###################### GATEWAY CONFIG ######################

  gateway-php84-service:
    container_name: gateway-retrospective
    build:
      context: .
      dockerfile: ./gateway/php/Dockerfile
    volumes:
      - ./gateway/app:/var/www/project
    networks:
      - retrospective-network
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1 #cs fixer still don't support php 8.4, fix flag

  gateway-nginx-service:
    image: nginx:stable-alpine
    container_name: gateway-retrospective-nginx
    ports:
      - "8081:80"
    volumes:
      - ./gateway/app:/var/www/project
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway-php84-service
    networks:
      - retrospective-network

  ################# NOTIFICATION SERVICE CONFIG #################

  # TODO -> SETUP Notification service

  ################# MAILER SERVICE CONFIG #######################

  # TODO -> SETUP Mailer service


volumes:
  mysql8-retrospective-data:


#ENV