networks:
  retrospective-network:

services:
  # MYSQL
  mysql8-service:
    image: mysql:8
    container_name: mysql8-retrospective-container
    ports:
      - "5306:3306"
    volumes:
      - mysql8-retrospective-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: retrospective_db
      MYSQL_USER: retrospective_user
      MYSQL_PASSWORD: admin12345
    networks:
      - retrospective-network

  # PHP_MY_ADMIN
  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    depends_on:
      - mysql8-service
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql8-service
      MYSQL_ROOT_PASSWORD: admin12345
    networks:
      - retrospective-network

  ######################## RABBIT MQ #########################

  retrospective-rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-retrospective
    restart: unless-stopped
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: retrospective
      RABBITMQ_DEFAULT_PASS: retrospective
    volumes:
      - retrospective-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - retrospective-network

  ######################## MAILER SERVICE  ##############################

  retrospective-mailhog-service:
    image: mailhog/mailhog
    container_name: mailhog-retrospective
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - retrospective-network

  ###################### GATEWAY CONFIG ######################

  gateway-php84-service:
    container_name: gateway-retrospective
    build:
      context: .
      dockerfile: ./gateway/php/Dockerfile
    volumes:
      - ./gateway/app:/var/www/project
    networks:
      - retrospective-network
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1 #cs fixer still don't support php 8.4, fix flag
      NOTIFICATIONS_API_URL: 'http://notification-nginx-service:80'
      NOTIFICATIONS_API_KEY: 'f8JhT7kL9pQ2mN4rX6yC1bV3zG5aW0oU'
      AMQP_DSN: 'amqp://retrospective:retrospective@retrospective-rabbitmq-service:5672'

  gateway-nginx-service:
    image: nginx:stable-alpine
    container_name: gateway-retrospective-nginx
    ports:
      - "8081:80"
    volumes:
      - ./gateway/app:/var/www/project
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway-php84-service
    networks:
      - retrospective-network

  ################# NOTIFICATION SERVICE CONFIG #################

  # TODO -> SETUP Notification service
  notification-php84-service:
    container_name: notification-retrospective
    build:
      context: .
      dockerfile: ./notification-service/php/Dockerfile
    volumes:
      - ./notification-service/app:/var/www/project
    networks:
      - retrospective-network
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1 #cs fixer still don't support php 8.4, fix flag
      API_KEY: 'f8JhT7kL9pQ2mN4rX6yC1bV3zG5aW0oU'
      AMQP_DSN: 'amqp://retrospective:retrospective@retrospective-rabbitmq-service:5672'

  notification-nginx-service:
    image: nginx:stable-alpine
    container_name: notification-retrospective-nginx
    ports:
      - "8082:80"
    volumes:
      - ./notification-service/app:/var/www/project
      - ./notification-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - notification-php84-service
    networks:
      - retrospective-network


volumes:
  mysql8-retrospective-data:
  retrospective-rabbitmq-data: