api_platform:
    title: Notification Service API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            apiKey:
                name: X-API-KEY
                type: header
