Mutation:
  type: object
  config:
    fields:
      testMutation:
        type: "dummyData"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\TestMutation::testMutation")'
      emailVerification:
        type: "SiteMessage"
        description: "Handles email verification using a verification token"
        args:
          verificationToken: "String!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\AuthMutation::emailVerificationTokenMutation", args)'