Mutation:
  type: object
  config:
    fields:
      emailVerification:
        type: "SiteMessage"
        description: "Handles email verification using a verification token"
        args:
          verificationToken: "String!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\AuthMutation::emailVerificationTokenMutation", args)'
      emailVerificationTokenResend:
        type: "SiteMessage"
        description: "Resends the email verification token to the user."
        args:
          email: "String!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\AuthMutation::emailVerificationTokenResendMutation", args)'