Query:
  type: object
  config:
    description: "User ORM repository"
    fields:
      testing:
        type: "dummyData"
        resolve: '@=query("App\\GraphQL\\Resolver\\TestResolver::getTest")'
