Query:
  type: object
  config:
    description: "User ORM repository"
    fields:
      user:
        type: "User"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::getUser")'
      retrospective:
        type: "Retrospective"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveResolver::getRetrospective", args)'
      retrospectives:
        type: "RetrospectiveCollectionResponse"
        args:
          filters: "RetrospectiveFiltersInput"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveResolver::getRetrospectives", args)'
      retrospectiveInvite:
        type: "RetrospectiveInvite"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveParticipantsResolver::getRetrospectiveInvite", args)'
      retrospectiveInvites:
        type: "RetrospectiveInviteCollectionResponse"
        args:
          filters: "RetrospectiveInviteFiltersInput"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveParticipantsResolver::getRetrospectiveInvites", args)'
      retrospectiveCard:
        type: "Card"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveCardResolver::getRetrospectiveCard", args)'
      participants:
        type: "ParticipantCollectionCollectionResponse"
        args:
          filters: "ParticipantFilterInput"
        resolve: '@=query("App\\GraphQL\\Resolver\\ParticipantResolver::getParticipants", args)'
      latestUserNotifications:
        type: "LatestUserNotificationsResponse"
        resolve: '@=query("App\\GraphQL\\Resolver\\NotificationResolver::resolveLatestUserNotifications")'
      userNotifications:
        type: "UserNotificationCollectionResponse"
        args:
          filters: "UserNotificationFiltersInput"
        resolve: '@=query("App\\GraphQL\\Resolver\\NotificationResolver::resolveUserNotifications", args)'