Query:
  type: object
  config:
    description: "User ORM repository"
    fields:
      user:
        type: "User"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::getUser")'
      retrospective:
        type: "Retrospective"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveResolver::getRetrospective", args)'
      retrospectives:
        type: "RetrospectiveCollectionResponse"
        args:
          filters: "RetrospectiveFiltersInput"
        resolve: '@=query("App\\GraphQL\\Resolver\\RetrospectiveResolver::getRetrospectives", args)'