Retrospective:
  type: object
  config:
    description: "Retrospective type definition"
    fields:
      id:
        type: "Int!"
        description: "The unique identifier of the retrospective"
      title:
        type: "String!"
        description: "The title of the retrospective"
      description:
        type: "String!"
        description: "The detailed description of the retrospective"
      startTime:
        type: "DateTime!"
        description: "The start time of the retrospective"
      status:
        type: "RetrospectiveStatus!"
        description: "The current status of the retrospective"
      createdAt:
        type: "DateTime!"
        description: "Timestamp of when the retrospective was created"
      updatedAt:
        type: "DateTime!"
        description: "Timestamp of the last update"
      retrospectiveParticipants:
        type: "[RetrospectiveParticipant]"
        description: "List of participants in the retrospective"
      cards:
        type: "[Card]"
        description: "List of cards associated with the retrospective"


RetrospectiveCollectionResponse:
  type: object
  config:
    description: "A paginated collection of retrospectives"
    fields:
      data:
        type: "[Retrospective]"
        description: "The list of retrospectives in the current page"
      pagination:
        type: "Pagination"
        description: "Pagination details for the current page"

RetrospectiveStatus:
  type: enum
  config:
    description: "Available statuses for a retrospective"
    values:
      scheduled:
        description: "Retrospective is scheduled to occur"
        value: scheduled
      finished:
        description: "Retrospective has been completed"
        value: finished
      cancelled:
        description: "Retrospective has been cancelled"
        value: cancelled

RetrospectiveCreateInput:
  type: input-object
  config:
    description: "Input type for creating a new retrospective"
    fields:
      title:
        type: "String!"
        description: "The title of the retrospective"
      description:
        type: "String!"
        description: "The detailed description of the retrospective"
      startTime:
        type: "DateTime!"
        description: "The start time of the retrospective"

RetrospectiveCreateResponse:
  type: object
  config:
    fields:
      success: "Boolean"
      errors: "ValidationError"
      retrospective: "Retrospective"

RetrospectiveUpdateInput:
  type: input-object
  config:
    fields:
      title:
        type: "String"
        description: "New title for the retrospective"
      description:
        type: "String"
        description: "New description for the retrospective"
      status:
        type: "RetrospectiveStatus"
        description: "New status for the retrospective"
      startTime:
        type: "DateTime"
        description: "New start time for the retrospective"

RetrospectiveUpdateResponse:
  type: object
  config:
    fields:
      success: "Boolean"
      errors: "ValidationError"
      retrospective: "Retrospective"

RetrospectiveFiltersInput:
  type: input-object
  config:
    fields:
      page:
        type: "Int"
        description: "Page number for pagination"
      itemsPerPage:
        type: "Int"
        description: "Number of items per page"
      isOwner:
        type: "Boolean"
        description: "Filter by ownership of the retrospective"
