gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 days
    token_parameter_name: refresh_token
    user_provider: app_user_provider
    firewall: main
