security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login_check
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            provider: app_user_provider
            stateless: true
            user_checker: App\Security\UserChecker
            entry_point: jwt
            jwt: ~
            refresh_jwt: ~

    access_control:
        - { path: '^/api/login_check', roles: PUBLIC_ACCESS }
        - { path: '^/api/token/refresh', roles: PUBLIC_ACCESS }
